apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wtvq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wtvq
    app.kubernetes.io/part-of: cin4s-839-0045-app
  name: devfile-sample-wtvq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wtvq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wtvq
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0045-tenant/cin4s-839-0045-app/devfile-sample-wtvq@sha256:a150e4a1debd83e3dc4f49ad1353c17f64a20ace6360ed4ce86bd4f52161c0fe
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
