apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wtvq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0045-tenant/cin4s-839-0045-app/devfile-sample-wtvq@sha256:a150e4a1debd83e3dc4f49ad1353c17f64a20ace6360ed4ce86bd4f52161c0fe
        name: my-nodejs
        resources: {}
status: {}
